### ISSUE TITLE
cf create-service-key bugs and errors

### ISSUE THREAD

**Issue by tanjoht** [jasonmimick/atlas-osb#48]
BUG: cf create-service-key -c '{"User" : {"roles" : [ { "roleName" : "readWriteAnyDatabase", "databaseName" : "admin"} ] } }' → will create the database user with both the default role and the requested role

ERROR: cf create-service-key -c '{"User" : {"roles" : [ { "roleName" : "readWrite", "databaseName" : "default"} ] } }' → specifying the database user with the same role and databaseName as the default will result in error

**Comment by jasonmimick** [comment]
Hi @tanjoht 
Please review the MongoDB Atlas documentation - user's can only be defined on the `admin` database.
https://docs.atlas.mongodb.com/security-add-mongodb-users/#database-user-authentication
This is working as designed.

Also - it would be helpful to enter a bit more descriptive notes for any issues. Just saying "BUG" doesn't really give any much to go on, let alone know what you're trying to do (since clearly in Atlas you cannot do this - like that).

Details
----
>BUG: cf create-service-key -c '{"User" : {"roles" : [ { "roleName" : "readWriteAnyDatabase", "databaseName" : "admin"} ] } }' → will create the database user with both the default role and the requested role
*Why does this work?
Because if there is not any `databaseName` in the `Bind()` parameters, we will set it to `admin` for Atlas.

Also - with a fresh install and cluster we *CANNOT* get any errors?

```bash
 cf create-service-key T121 Uuu1 -c '{"User" : { "databaseName" : "admin","roles" : [ { "roleName" : "readWrite", "databaseName" : "default"} ] } }'
Creating service key Uuu1 for service instance T121 as admin...
OK

➜  atlas-osb git:(master) ✗ cf create-service-key T121 VVVw -c '{"User" : { "roles" : [ { "roleName" : "readWrite", "databaseName" : "default"} ] } }'Creating service key VVVw for service instance T121 as admin...
OK
```

Note - it works when I specify the `databaseName` or not.
And here is the proof of what's get's created in Atlas:
```bash

➜  atlas-osb git:(master) ✗ mongocli atlas dbusers list
[
        {
                "databaseName": "admin",
                "ldapAuthType": "NONE",
                "x509Type": "NONE",
                "groupId": "5f2152182f51736b9e538a25",
                "roles": [
                        {
                                "roleName": "readWrite",
                                "databaseName": "default"
                        }
                ],
                "username": "test-user"
        },
        {
                "databaseName": "admin",
                "ldapAuthType": "NONE",
                "x509Type": "NONE",
                "groupId": "5f2152182f51736b9e538a25",
                "roles": [
                        {
                                "roleName": "readWrite",
                                "databaseName": "default"
                        }
                ],
                "username": "8fb1c110-de7e-4cf2-8389-b9ffbf39a484"
        },
        {
                "databaseName": "admin",
                "ldapAuthType": "NONE",
                "x509Type": "NONE",
                "groupId": "5f2152182f51736b9e538a25",
                "roles": [
                        {
                                "roleName": "readWrite",
                                "databaseName": "default"
                        }
                ],
                "username": "36788292-9b19-426f-bca3-ee3b424f124d"
        }
]
```
